[package]
name = "simple-smtp-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.22"
env_logger = "0.11.5"
chrono = "0.4"
rustls = "0.21.0"
tokio = { version = "1.28", features = ["full"] }
tokio-rustls = "0.24"
rustls-pemfile = "1.0"
webpki-roots = "0.25.2"